### ISSUE TITLE
admsAppLibrary.a arm64 architecture

### ISSUE THREAD

**Issue by ShadyGhalab** [danielctull-forks/Omniture-SDK-iOS#1]
when omniture will support arm64 and what the solution for run it on arm64 devices ?

**Comment by ghost** [comment]
Is it still something we're waiting for?

**Comment by MSPFamily** [comment]
HI We are using 32-bit of admsAppLibrary.a we are looking for 64 bit arch. may i know when will be released? We have to push the app for iOS 8 sooner.

**Comment by shivakumargouda** [comment]
@ShadyGhalab any updates on the 64 bit library yet??
